/* eslint-disable react/no-unescaped-entities */
import { Link } from 'react-router-dom'

function Page_Shipping() {
  return (
    <div className='Page_Shipping w-screen max-h-[1000vh] h-auto mt-12 pb-12 bg-gradient-to-b from-gray-100 to-neutral-300'>
      <div className='ShippingDocumentWrapper w-3/4 mx-auto text-base'>
        <h1 className='text-xl font-bold underline underline-offset-8'>
          Shipping Policy
        </h1> 
        <br/>
        <span>
          Our Shipping Policy was last updated on 2/27/2024.
        </span>
        <br/>
        <br/>
        <h2 className='text-xl font-bold underline underline-offset-8'>
          Interpretation and Definitions
        </h2> 
        <br/>
        <h3 className='text-lg font-bold'>
          Interpretation
        </h3> 
        <br/>
        <span>
          The words of which the initial letter is capitalized 
          have meanings defined under the following conditions. 
          The following definitions shall have the same meaning 
          regardless of whether they appear in singular or in plural.
        </span>
        <br/>
        <br/>
        <h3 className='text-lg font-bold'>
          Definitions
        </h3>
        <br/>
        <span>
          For the pruposes of this Disclaimer:
        </span>
        <br/>
        <br/>
        <ul className='list-disc'>
          <li>
            "<b>Company</b>" (referred to as either "the Company", "We", "Us" or "Our" in this Disclaimer) refers to 
            SnapStory 
          </li>
          <li>
            "<b>Goods</b>" refers to the items offered for sale on the Service.
          </li>
          <li>
            "<b>Orders</b>" means a request by You to purchase Goods from Us.
          </li>
          <li>
            "<b>Service</b>" refers to the Website.
          </li>
          <li>
            "<b>Website</b>" refers to SnapStory, accessible from SnapStory.com.
          </li>
          <li>
            "<b>You</b>" means the individual accessing the Service, 
            or the company, or other legal entity on behalf of which 
            such individual is accessing or using the Service, as applicable.
          </li>
        </ul>
        <br/>
        <span>
          Thank you for visiting and shopping at SnapStory.com. 
          The following terms and conditions constitute our Shipping Policy. 
          This Shipping was generated by TermsFeed Shipping Policy Generator.
        </span>
        <br/><br/>
        <h1 className='text-xl font-bold underline underline-offset-8'>
          Contact Us
        </h1> 
        <br/>
        <span>
          If you have any questions about this 
          Shipping Policy, You can contact Us:
        </span>
        <br/><br/>
        <ul className='list-disc'>
          <li>
            By visiting this page on our website: <Link to={"/"} className='underline'>www.SnapStory.com</Link>
          </li>
          <li>
            By sending us an email: myEmail12345@gmail.com 
          </li>
        </ul>
      </div>
    </div>
  )
}

export default Page_Shipping
